server:
  port: 7777
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eden_connect?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: yuki
    password: ayase
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
upload:
  avatar-path: D:\code\Project\EdenConnect\eden-connect-java\src\main\resources\upload\avatar\
  img-path: D:\code\Project\EdenConnect\eden-connect-java\src\main\resources\upload\img\
#  configuration:
#    map-underscore-to-camel-case: true
